USE RAYEN
GO
/* INSERTAR ELEMENTO A LA TAU */
declare @descripcion varchar(250)
set @descripcion = 'Mordedura de animal'

if (select COUNT(*) from TAU_TIPO_ACCIDENTE_URGENCIA where DESCRIPCION = @descripcion) = 0
begin
	insert into TAU_TIPO_ACCIDENTE_URGENCIA 
	(DESCRIPCION, ACTIVO, ELIMINADO) values
	(@descripcion, 1, 0)
	print 'creado con éxito'
end
else
begin
	print 'YA EXISTE, NO SE PUEDE CREAR'
end
GO
/* SE DEBE AGREGAR UNA COLUMNA QUE ALMACENE EL TIPO DE MORDEDURA
	DE ANIMAL, ESTA COLUMNA POR DEFECTO SERA CON VALOR 0, ES UN ENUMERADO
*/
IF NOT EXISTS(
        SELECT *
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'IURG_INGRESO_URGENCIA' AND COLUMN_NAME = 'TMA_ID'
    )
    BEGIN
        ALTER TABLE IURG_INGRESO_URGENCIA
		ADD TMA_ID int NOT NULL DEFAULT(0)
    END
	ELSE
	BEGIN
		PRINT 'YA EXISTE, NO ES NECESARIO CREAR LA COLUMNA'
	END



GO