use RAYEN
go
IF NOT EXISTS(
        SELECT *
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'RL_ACT_URG' AND COLUMN_NAME = 'TIPO'
    )
    BEGIN
        ALTER TABLE RL_ACT_URG
		ADD TIPO int NOT NULL DEFAULT(0)
    END
	ELSE
	BEGIN
		PRINT 'YA EXISTE, NO ES NECESARIO CREAR LA COLUMNA'
	END

GO
--AHORA REALIZAMOS UN UPDATE A TODOS LOS ELEMENTOS DE LA RELACION PARA DEJAR EL TIPO EN VIOLENCIA
UPDATE RL_ACT_URG SET TIPO = 1
GO
--AHORA QUE LA COLUMNA ESTA CREADA PROCEDEMOS A REALIZAR LOS INSERTS QUE CORRESPONDEN
--SOLO FALTAN AGREGAR LOS DE ANTICONCEPCION Y EL NUEVO ELEMENTO DE VIOLENCIA INTRAFAMILIAR
IF (SELECT COUNT(*) FROM RL_ACT_URG WHERE ACT_ID = 7072) = 0
BEGIN 
--INSERT DE CONSULTA ANTICONCEPCION DE EMERGENCIA CON ENTREGA PAE
INSERT INTO RL_ACT_URG (ACT_ID, ACTIVO_URGENCIA, TIPO) VALUES (7072, 1, 2)

END
GO
IF (SELECT COUNT(*) FROM RL_ACT_URG WHERE ACT_ID = 7073) = 0
BEGIN 
--INSERT DE CONSULTA ANTICONCEPCION DE EMERGENCIA SIN ENTREGA PAE
INSERT INTO RL_ACT_URG (ACT_ID, ACTIVO_URGENCIA, TIPO) VALUES (7073, 1, 2)

END
GO
IF (SELECT COUNT(*) FROM RL_ACT_URG WHERE ACT_ID = 10594) = 0
BEGIN 
--INSERT VIOLENACIA INTRAFAMILIAR
INSERT INTO RL_ACT_URG (ACT_ID, ACTIVO_URGENCIA, TIPO) VALUES (10594, 1, 1)

END
