USE [master]
GO

/****** Object:  Database [SALUD_TE_INTEGRA]    Script Date: 13/03/2018 22:03:31 ******/
DROP DATABASE [SALUD_TE_INTEGRA]
GO

/****** Object:  Database [SALUD_TE_INTEGRA]    Script Date: 13/03/2018 22:03:31 ******/
CREATE DATABASE [SALUD_TE_INTEGRA] ON  PRIMARY 
( NAME = N'SALUD_TE_INTEGRA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER2\MSSQL\DATA\SALUD_TE_INTEGRA.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SALUD_TE_INTEGRA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER2\MSSQL\DATA\SALUD_TE_INTEGRA_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SALUD_TE_INTEGRA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET ARITHABORT OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET RECOVERY FULL 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET  MULTI_USER 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SALUD_TE_INTEGRA] SET  READ_WRITE 
GO

