USE [RAYEN]
GO

/*TABLA CAR_CARACTERISTICA_ARTICULO */

/****** Object:  Table [dbo].[CAR_CARACTERISTICA_ARTICULO]    Script Date: 14-01-2019 8:45:20 ******/
IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'CAR_CARACTERISTICA_ARTICULO')
BEGIN

	/****** Object:  Table [dbo].[CAR_CARACTERISTICA_ARTICULO]    Script Date: 14-01-2019 8:45:20 ******/
	SET ANSI_NULLS ON

	SET QUOTED_IDENTIFIER ON

	CREATE TABLE [dbo].[CAR_CARACTERISTICA_ARTICULO](
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[ARTI_ID] [int] NULL,
		[ALIAS] [varchar](500) NULL,
		[NOD_ID] [int] NULL,
		[ES_GES] [int] NULL,
		[ACTIVO] [int] NULL,
		[ELIMINADO] [int] NULL,
	 CONSTRAINT [PK_CAR_CARACTERISTICA_ARTICULO] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

end

/*TABLA RL_INS_ARTI */
/****** Object:  Table [dbo].[RL_INS_ARTI]    Script Date: 14-01-2019 8:45:20 ******/
IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'RL_INS_ARTI')
BEGIN
	/****** Object:  Table [dbo].[RL_INS_ARTI]    Script Date: 14-01-2019 8:48:35 ******/
	SET ANSI_NULLS ON

	SET QUOTED_IDENTIFIER ON

	CREATE TABLE [dbo].[RL_INS_ARTI](
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[ARTI_ID] [int] NULL,
		[INS_ID] [int] NULL,
	 CONSTRAINT [PK_RL_INS_ARTI] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

end


/*TABLA RL_INSUMO_ARTI */
/****** Object:  Table [dbo].[RL_INSUMO_ARTI]    Script Date: 14-01-2019 8:45:20 ******/
IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'RL_INSUMO_ARTI')
BEGIN
	/****** Object:  Table [dbo].[RL_INSUMO_ARTI]    Script Date: 14-01-2019 8:51:07 ******/
	SET ANSI_NULLS ON

	SET QUOTED_IDENTIFIER ON

	CREATE TABLE [dbo].[RL_INSUMO_ARTI](
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[ARTI_ID] [int] NULL,
		[INSUMO_ID] [int] NULL,
	 CONSTRAINT [PK_RL_INSUMO_ARTI] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

end

/*TABLA RL_PSAL_ARTI */
/****** Object:  Table [dbo].[RL_PSAL_ARTI]    Script Date: 14-01-2019 8:45:20 ******/
IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'RL_PSAL_ARTI')
BEGIN

	/****** Object:  Table [dbo].[RL_PSAL_ARTI]    Script Date: 14-01-2019 8:53:47 ******/
	SET ANSI_NULLS ON

	SET QUOTED_IDENTIFIER ON

	CREATE TABLE [dbo].[RL_PSAL_ARTI](
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[ARTI_ID] [int] NULL,
		[PSAL_ID] [int] NULL,
		[ID_PADRE] [int] NULL,
		[NOD_ID] [int] NULL,
	 CONSTRAINT [PK_RL_PSAL_ARTI] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]


END

