
/*

CREADO POR VICTOR CORONADO EN ATENCIÓN AL REQUERIMIENTO 167694 DE MANTENEDORES
DONDE SE AGREGAN NUEVAS FUNCIONALIDADES A LOS ARTICULOS HIJOS, ESTAS FUNCIONALIDADES
SON AGREGAR CARACTERSTICAS COMO GES, AGREGAR ALIAS, RESTRINGIR ARSENAL Y VINCULAR
INSUMOS

10-01-2018

*/

use RAYEN
go

--PARAMETRO PERMITE_AGREGAR_ALIAS
if (select COUNT(*) from MPY_MAESTRO_PARAMETROS_RAYEN where NOMBRE = 'PERMITE_AGREGAR_ALIAS') = 0
begin
	--NO EXISTE HAY QUE INSERTARLO
	insert into MPY_MAESTRO_PARAMETROS_RAYEN 
		(MTP_ID, NOMBRE, DESCRIPCION, CREADO_POR, ACTIVO, ELIMINADO, FECHA_CREACION, FECHA_CREACION_ENTERO)
		values
		(3, 'PERMITE_AGREGAR_ALIAS', 'Este parámetro sirve para permitir generar alias a los articulos hijos (POC)','Victor Coronado', 1, 0, GETDATE(), CAST(CONVERT(VARCHAR, GETDATE(),112) AS INT))
	--PRINT INFORMATIVO
	PRINT('MPY PERMITE_AGREGAR_ALIAS, INSERTADO CON EXITO')
end
--PARAMETRO RESTRINGE_ARSENAL
if (select COUNT(*) from MPY_MAESTRO_PARAMETROS_RAYEN where NOMBRE = 'RESTRINGE_ARSENAL') = 0
begin
	insert into MPY_MAESTRO_PARAMETROS_RAYEN 
		(MTP_ID, NOMBRE, DESCRIPCION, CREADO_POR, ACTIVO, ELIMINADO, FECHA_CREACION, FECHA_CREACION_ENTERO)
		values
		(3, 'RESTRINGE_ARSENAL', 'Este parámetro sirve para restringir arsenal a los articulos hijos (POC)','Victor Coronado', 1, 0, GETDATE(), CAST(CONVERT(VARCHAR, GETDATE(),112) AS INT))
			--PRINT INFORMATIVO
	PRINT('MPY RESTRINGE_ARSENAL, INSERTADO CON EXITO')
end
--PARAMETRO PERMITE_VINCULAR_INSUMO
if (select COUNT(*) from MPY_MAESTRO_PARAMETROS_RAYEN where NOMBRE = 'PERMITE_VINCULAR_INSUMO') = 0
begin
		insert into MPY_MAESTRO_PARAMETROS_RAYEN 
		(MTP_ID, NOMBRE, DESCRIPCION, CREADO_POR, ACTIVO, ELIMINADO, FECHA_CREACION, FECHA_CREACION_ENTERO)
		values
		(3, 'PERMITE_VINCULAR_INSUMO', 'Este parámetro sirve para vincular insumos a los articulos hijos (POC)','Victor Coronado', 1, 0, GETDATE(), CAST(CONVERT(VARCHAR, GETDATE(),112) AS INT))
		--PRINT INFORMATIVO
	PRINT('MPY PERMITE_VINCULAR_INSUMO, INSERTADO CON EXITO')
end
--PARAMETRO ARTICULO_PATOLOGIA_GES
if (select COUNT(*) from MPY_MAESTRO_PARAMETROS_RAYEN where NOMBRE = 'ARTICULO_PATOLOGIA_GES') = 0
begin
		insert into MPY_MAESTRO_PARAMETROS_RAYEN 
		(MTP_ID, NOMBRE, DESCRIPCION, CREADO_POR, ACTIVO, ELIMINADO, FECHA_CREACION, FECHA_CREACION_ENTERO)
		values
		(3, 'ARTICULO_PATOLOGIA_GES', 'Este parámetro sirve para GES (POC)','Victor Coronado', 1, 0, GETDATE(), CAST(CONVERT(VARCHAR, GETDATE(),112) AS INT))
		--PRINT INFORMATIVO
	PRINT('MPY ARTICULO_PATOLOGIA_GES, INSERTADO CON EXITO')
end