/************************************************************************
AUTOR: Víctor Coronado
FECHA DE CREACIÓN: 16/11/2018
BASE DE DATOS: BDWEBLUN
OBJETIVO: REPARACIÓN DE USUARIOS LUN ACTIVOS Y ELIMINADOS A ELIMINADOS
FECHA DE MODIFICACIÓN: 
USUARIO DE MODIFICACIÓN: 
MOTIVO DE MODIFICACIÓN: 
VISADO POR (QA): 
FECHA APROBACIÓN QA: 
COMENTARIOS QA: 
VISADO POR (DBA): 
FECHA APROBACIÓN DBA: 
COMENTARIOS DBA: 
TABLAS INVOLUCRADAS: RELUN_REGISTRO_LUN
***********************************************************************/
USE BDWebLun
GO
UPDATE RELUN_REGISTRO_LUN SET ACTIVO = 0 WHERE ACTIVO = 1 AND ELIMINADO = 1
