
USE RAYEN 
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[REP0080]') AND type = N'P') 
	exec('CREATE PROCEDURE [dbo].[REP0080] AS BEGIN SET NOCOUNT ON; END')
GO
/************************************************************************                              
NOMBRE DEL PROCEDIMIENTO	: REP0080             
AUTOR						: Elias Orellana
FECHA DE CREACIÓN			: 06/02/2013
BASE DE DATOS				: RAYEN                             

OBJETIVO					: REPORTE EGRESOS DE PROGRAMA POR RANGO DE FECHA POR NODO

FECHA DE MODIFICACIÓN		: 12/02/2013
USUARIO DE MODIFICACIÓN		: Pablo Serrano
MOTIVO DE MODIFICACIÓN		: Implementacion del codigo especificado

FECHA DE MODIFICACIÓN		: 18/05/2016
USUARIO DE MODIFICACIÓN		: JAIME LEÓN
MOTIVO DE MODIFICACIÓN		: correccion de informe, ahora toma en cuenta ademas del estado de egreso, toma tambien en cuenta al prog_id.

FECHA DE MODIFICACIÓN		: 07/07/2016
USUARIO DE MODIFICACIÓN		: VÍCTOR CORONADO
MOTIVO DE MODIFICACIÓN		: CORRECCIÓN POR RECHAZO, LOS REGISTROS SE DUPLICABAN EN ALGUNOS CASOS, SE APLICA USN.ACTIVO = 1.

FECHA DE MODIFICACIÓN		: 08/07/2016
USUARIO DE MODIFICACIÓN		: VÍCTOR CORONADO
MOTIVO DE MODIFICACIÓN		: CORRECCIÓN POR RECHAZO, LOS REGISTROS SE DUPLICABAN EN ALGUNOS CASOS, SE AGREGA JOIN CON EL PROGRAMA
							: DETECTADO POR QA.

VISADO POR (QA)  			:   
FECHA APROBACIÓN QA 		:   
COMENTARIOS QA     			:                             

VISADO POR (DBA)  			:   
FECHA APROBACIÓN DBA 		:   
COMENTARIOS DBA     		:                
                              
TABLAS INVOLUCRADAS 		: 
***********************************************************************/
ALTER PROCEDURE [dbo].[REP0080]
(
	@NOD_ID INT,
	@FECHA_INICIO DATETIME,
	@FECHA_TERMINO DATETIME,
	@PROG_ID INT
)
AS
BEGIN
SELECT
USP.RUT,
USP.NOMBRES,
USP.APELLIDO_PATERNO,
USP.APELLIDO_MATERNO,
RAYEN.DBO.EDAD_EXACTA (USP.FECHA_DE_NACIMIENTO, GETDATE())/10000 AS EDAD_ANOS,
RAYEN.DBO.EDAD_EXACTA (USP.FECHA_DE_NACIMIENTO, GETDATE())/100%100 AS EDAD_MESES,
RAYEN.DBO.EDAD_EXACTA (USP.FECHA_DE_NACIMIENTO, GETDATE())%100 AS EDAD_DIAS,
CASE
        WHEN USP.HL7_0001_U_ID = 2 THEN 'FEMENINO'
        WHEN USP.HL7_0001_U_ID = 3 THEN 'MASCULINO'
END AS SEXO,
USP.FECHA_DE_NACIMIENTO,
SEC.NOMBRE AS SECTOR,
FAM.CALLE + ' ' + FAM.CASA +' '+ CASE FAM.BLOCK WHEN NULL THEN '' WHEN '' THEN '' ELSE 'BLOCK '+ FAM.BLOCK END +' '+ CASE FAM.DEPTO WHEN NULL THEN '' WHEN '' THEN '' ELSE 'DEPTO '+ FAM.DEPTO END +' '+ CASE FAM.VILLA_POBLACION WHEN NULL THEN '' WHEN '' THEN '' ELSE 'POBLACION '+ FAM.VILLA_POBLACION END 'DIRECCION',  
HAPS.NOMBRE_PROGRAMA,
CASE
	WHEN HAPS.ESTADO = 3 THEN 'EGRESO POR ABANDONO'
	WHEN HAPS.ESTADO = 4 THEN 'EGRESO POR ALTA'
	WHEN HAPS.ESTADO = 5 THEN 'EGRESO POR TRASLADO'
	WHEN HAPS.ESTADO = 6 THEN 'EGRESO AL SISTEMA PRIVADO'
    WHEN HAPS.ESTADO = 7 THEN 'EGRESO POR FALLECIMIENTO'
    WHEN HAPS.ESTADO = 9 THEN 'EGRESO POR FRACASO'
    WHEN HAPS.ESTADO = 10 THEN 'EGRESO POR CAMBIO ETAREO'
    WHEN HAPS.ESTADO = 11 THEN 'EGRESO POR ALTA EDUCATIVA'
    WHEN HAPS.ESTADO = 12 THEN 'EGRESO POR ALTA PREVENTIVA'
    WHEN HAPS.ESTADO = 13 THEN 'EGRESO POR ALTA INTEGRAL'
    WHEN HAPS.ESTADO = 14 THEN 'EGRESO DISCIPLINARIO'
    WHEN HAPS.ESTADO = 15 THEN 'EGRESO POR ALTA DE SEGUIMIENTO'
    WHEN HAPS.ESTADO = 16 THEN 'EGRESO POR PASIVACION'
END AS ESTADO_PROGRAMA,
convert(datetime,HAPS.FECHA_HORA,111) AS FECHA_EGRESO,
FNP.NOMBRES AS NOMBRE_PROFESIONAL,
FNP.APELLIDO_PATERNO AS PATERNO_PROFESIONAL,
FNP.APELLIDO_MATERNO AS MATERNO_PROFESIONAL

FROM RAYEN..USPC_USUARIO_APS_BAJO_CONTROL HAPS

INNER JOIN
        (SELECT
        PROG_ID,
         USP_ID,
         MAX (FECHA_HORA) AS FECHA_HORA
         FROM RAYEN..USPC_USUARIO_APS_BAJO_CONTROL HAPS
         WHERE
         (HAPS.ESTADO IN (3,4,5,6,7,9,10,11,12,13,14,15,16) AND
         HAPS.FECHA_HORA BETWEEN @FECHA_INICIO AND  @FECHA_TERMINO AND
         HAPS.ELIMINADO = 0)
         GROUP BY
         PROG_ID,
         USP_ID) AS RESUL ON
         HAPS.USP_ID = RESUL.USP_ID AND HAPS.FECHA_HORA = RESUL.FECHA_HORA AND RESUL.PROG_ID = HAPS.PROG_ID

INNER JOIN RAYEN..USN_USUARIO_NODO USN ON USN.NOD_ID=@NOD_ID AND HAPS.USP_ID=USN.USP_ID  
--AND USN.ACTIVO = 1 

INNER JOIN RAYEN..USP_USUARIO_APS USP ON
USN.USP_ID = USP.ID AND USP.ELIMINADO=0

INNER JOIN RAYEN..FAM_FAMILIA FAM ON
USN.FAM_ID = FAM.ID

INNER JOIN RAYEN..SEC_SECTOR SEC ON
FAM.SEC_ID = SEC.ID

INNER JOIN RAYEN..FNP_FUNCIONARIO_PRESTADOR FNP ON
HAPS.FNP_ID = FNP.ID


WHERE
HAPS.NOD_ID = @NOD_ID
AND (HAPS.ESTADO IN (3,4,5,6,7,9,10,11,12,13,14,15,16) AND
HAPS.FECHA_HORA BETWEEN @FECHA_INICIO AND  @FECHA_TERMINO AND
HAPS.ELIMINADO = 0) AND
(@PROG_ID = 0 OR CASE COALESCE(HAPS.PROG_ID,0) WHEN 0 THEN -1 ELSE HAPS.PROG_ID END = @PROG_ID) AND
HAPS.ELIMINADO = 0 
ORDER BY
HAPS.NOMBRE_PROGRAMA
END


GO



