USE RAYEN

declare @tabla table (ID INT IDENTITY NOT NULL PRIMARY KEY, id_mensaje int, xml_contenido xml, TIPO_MENSAJE INT, OBSERVACION VARCHAR(MAX), SDD_ID INT, FECHA_HORA_SERVIDOR DATETIME)

declare @result table (SOIN_ID int, ROL_GENERADOR VARCHAR(100), FNP_GENERADOR VARCHAR(250), ESTADO_OBSERVACION INT, OBSERVACION VARCHAR(MAX), SDD_ID INT, FECHA_HORA_SERVIDOR DATETIME)

insert into @tabla
select
	ID_MENSAJE,  
	CAST(CAST(contenido_xml as nvarchar(max)) as XML),
	TIPO_MENSAJE,
	MENSAJE_ERROR,
	SDD_ID,
	FECHA_HORA_SERVIDOR
	from  
	SAYDEX_INTEGRACION..COLA_ERROR_INTEGRACION 
	WHERE
	FECHA_HORA_SERVIDOR > CONVERT(DATETIME, '2016-05-19 13:00.000')
	and MENSAJE_ERROR is not null
	and MENSAJE_ERROR <> ''
	and TIPO_MENSAJE IN (1)


declare @max_id int
DECLARE @CONTADOR INT

SET @CONTADOR = 1
set @max_id = (select max(ID) from @tabla)

--SELECT @MAX_ID

DECLARE @ID_1 INT, @FNP_ID1 INT, @ROL_ID1 INT, @NOMBRE_FNP VARCHAR(250), @SDD_ID1 INT
WHILE (@CONTADOR <= @max_id)
BEGIN
	--SET @ID_1 = (SELECT B.xml_contenido.value('(SICEspecialidad/IdSICEnSistemaOrigen)[1]','VARCHAR(100)') FROM @tabla b WHERE ID = @CONTADOR)
	SET @ID_1 = (SELECT id_mensaje FROM @tabla b WHERE ID = @CONTADOR)
	SET @FNP_ID1 = 0
	SET @ROL_ID1 = 0
	SET @NOMBRE_FNP ='Servidor-Rechazo Corrección de Data'
	SET @SDD_ID1 = (SELECT SDD_ID FROM @tabla WHERE ID = @CONTADOR)
	--SET @ROL_ID1 = 0
	INSERT INTO @result
	SELECT 
		@ID_1,
		@ROL_ID1,
		@NOMBRE_FNP,
		1,
		B.OBSERVACION,
		B.SDD_ID,
		B.FECHA_HORA_SERVIDOR
	FROM @tabla b
		
	WHERE ID = @CONTADOR

PRINT @CONTADOR

SET @CONTADOR = @CONTADOR + 1

END

INSERT INTO OSE_OBSERVACION_SECUNDARIA (SOIN_ID, FECHA_REGISTRO_OBSERVACION, ROL_GENERADOR, NOMBRE_FNP_GENERADOR, ESTADO_OBSERVACION, OBSERVACION, SDD_ID, ELIMINADO)
	SELECT DISTINCT SOIN_ID, FECHA_HORA_SERVIDOR, ROL_GENERADOR, FNP_GENERADOR, 1, OBSERVACION, SDD_ID, 0 FROM @result 