
/*
SCRIPT DE REPARACIÓN DE UN USUARIO APS AL CUAL NO SE LE PUEDE
INTEGRAR PORQUE FALTA EL CODIGO DE REGION
CREADO POR VICTOR CORONADO, 24-06-2016

*/

USE RAYEN
--ACTUALIZAMOS LA SOINC PARA QUE QUEDE EN ESTADO RECHAZADA POR SISTEMA
update SOIN_SOLICITUD_INTERCONSULTA set ESTADO = 30 where id = 4695896

--AHORA ELIMINAMOS LOGICAMENTE UN REGISTRO DE LA GRU
--PARA QUE NO SEA CONSIDERADO AL MOMENTO DE EVALUAR
--LOS TIPOS DE GEOREFERENCIA, DE ESTA FORMA NOS ASEGU-
--RAMOS DE QUE EVALÚE EL TIPO 1 Y 3 Y PERMITA CORRECTAMENTE
--ESCRIBIR EL REGISTRO EN LA COLA DE INTEGRACION

UPDATE GRU_GEOREFERENCIA_USUARIO SET ELIMINADO = 1 WHERE ID = 6358920
