/*

QUERY CREADA PARA ELIMINAR LOS FUNCIONARIOS
PRESTADOR QUE CUENTAN CON EL ROL DE ANULADOR DE 
ATENCIONES EN EL SISTEMA, AL MISMO TIEMPO DEJA
EL ROL ELIMINADO DE FORMA LOGICA

CREADO POR VICTOR CORONADO 22-06-2016
POR NOTIFICACION DE SERVICIOS DE QUE
EL MODULO SE ENCUENTRA HABILITADO


*/

USE RAYEN

DELETE
RL_PFUROL
from 
RL_PFUROL rl 
inner join ROL_ROL rol on rol.ID = rl.ROL_ID
where rol.NOMBRE like '%AnuladorDeAtenciones%'

update ROL_ROL set ELIMINADO = 1 where NOMBRE = 'AnuladorDeAtenciones'