USE [RAYEN]
GO

/****** Object:  Table [dbo].[CAR_CARACTERISTICA_ARTICULO]    Script Date: 17-12-2018 16:23:03 ******/
DROP TABLE [dbo].[CAR_CARACTERISTICA_ARTICULO]
GO

/****** Object:  Table [dbo].[CAR_CARACTERISTICA_ARTICULO]    Script Date: 17-12-2018 16:23:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAR_CARACTERISTICA_ARTICULO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ARTI_ID] [int] NULL,
	[ALIAS] [varchar](500) NULL,
	[NOD_ID] [int] NULL,
	[ES_GES] [smallint] NULL,
	[ACTIVO] [smallint] NULL,
	[ELIMINADO] [smallint] NULL,
 CONSTRAINT [PK_CAR_CARACTERISTICA_ARTICULO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[RL_PSAL_ARTI]    Script Date: 17-12-2018 16:25:18 ******/
DROP TABLE [dbo].[RL_PSAL_ARTI]
GO


/****** Object:  Table [dbo].[RL_PSAL_ARTI]    Script Date: 20-12-2018 9:01:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RL_PSAL_ARTI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ARTI_ID] [int] NULL,
	[PSAL_ID] [int] NULL,
	[ID_PADRE] [int] NULL,
	[NOD_ID] [int] NULL,
 CONSTRAINT [PK_RL_PSAL_ARTI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




/****** Object:  Table [dbo].[RL_INSUMO_ARTI]    Script Date: 17-12-2018 16:26:46 ******/
DROP TABLE [dbo].[RL_INSUMO_ARTI]
GO

/****** Object:  Table [dbo].[RL_INSUMO_ARTI]    Script Date: 17-12-2018 16:26:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RL_INSUMO_ARTI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ARTI_ID] [int] NULL,
	[INSUMO_ID] [int] NULL,
 CONSTRAINT [PK_RL_INSUMO_ARTI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[RL_INS_ARTI]    Script Date: 21-12-2018 9:47:50 ******/
DROP TABLE [dbo].[RL_INS_ARTI]
GO

/****** Object:  Table [dbo].[RL_INS_ARTI]    Script Date: 21-12-2018 9:47:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RL_INS_ARTI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ARTI_ID] [int] NULL,
	[INS_ID] [int] NULL,
 CONSTRAINT [PK_RL_INS_ARTI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RAR_RESTRICCION_ARTICULO] DROP CONSTRAINT [FK_RAR_RELATION_HL7_0001]
GO

ALTER TABLE [dbo].[RAR_RESTRICCION_ARTICULO] DROP CONSTRAINT [FK_RAR_RELATION_ARTI]
GO

/****** Object:  Table [dbo].[RAR_RESTRICCION_ARTICULO]    Script Date: 21-12-2018 9:48:44 ******/
DROP TABLE [dbo].[RAR_RESTRICCION_ARTICULO]
GO

/****** Object:  Table [dbo].[RAR_RESTRICCION_ARTICULO]    Script Date: 21-12-2018 9:48:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RAR_RESTRICCION_ARTICULO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ARTI_ID] [int] NOT NULL,
	[SEX_ID] [int] NOT NULL,
	[EDAD_INFERIOR] [int] NOT NULL,
	[EDAD_SUPERIOR] [int] NOT NULL,
	[CANTIDAD_MINIMA_DIARIA] [int] NOT NULL,
	[CANTIDAD_MAXIMA_DIARIA] [int] NOT NULL,
	[ELIMINADO] [smallint] NOT NULL,
	[TID] [timestamp] NOT NULL,
 CONSTRAINT [PK_RAR_RESTRICCION_ARTICULO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RAR_RESTRICCION_ARTICULO]  WITH CHECK ADD  CONSTRAINT [FK_RAR_RELATION_ARTI] FOREIGN KEY([ARTI_ID])
REFERENCES [dbo].[ARTI_ARTICULO] ([ID])
GO

ALTER TABLE [dbo].[RAR_RESTRICCION_ARTICULO] CHECK CONSTRAINT [FK_RAR_RELATION_ARTI]
GO

ALTER TABLE [dbo].[RAR_RESTRICCION_ARTICULO]  WITH CHECK ADD  CONSTRAINT [FK_RAR_RELATION_HL7_0001] FOREIGN KEY([SEX_ID])
REFERENCES [dbo].[HL7_0001_U] ([ID])
GO

ALTER TABLE [dbo].[RAR_RESTRICCION_ARTICULO] CHECK CONSTRAINT [FK_RAR_RELATION_HL7_0001]
GO




