USE [RAYEN]
GO
/****** Object:  Table [dbo].[RL_TDA_ST]    Script Date: 21/05/2018 22:07:22 ******/
IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'RL_TDA_ST')
BEGIN
    SET QUOTED_IDENTIFIER ON


CREATE TABLE [dbo].[RL_TDA_ST](
	[TDA_ID] [int] NULL,
	[ELIMINADO] [int] NULL
) ON [PRIMARY]
END


