USE [BDWebLun]
GO
	IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ENCO0001]') AND type = N'P') 
	--Se crea encabezado vacio del SP en caso de ser nuevo
	exec('CREATE PROCEDURE [dbo].[ENCO0001] AS BEGIN SET NOCOUNT ON; END')
GO
/****** Object:  StoredProcedure [dbo].[ENCO0001]    Script Date: 01-06-2018 16:45:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/************************************************************************
NOMBRE DEL PROCEDIMIENTO: ENCO0001
AUTOR: Victor Coronado
FECHA DE CREACIÓN: 06/06/2018
BASE DE DATOS: BDWEBLUN
OBJETIVO: ACTUALIZA UN ELEMENTO EN LA TABLA ENCO_ENTIDAD_CONTRATANTE Y REBALSE LUN
FECHA DE MODIFICACIÓN: 
USUARIO DE MODIFICACIÓN: 
MOTIVO DE MODIFICACIÓN: 
VISADO POR (QA): 
FECHA APROBACIÓN QA: 
COMENTARIOS QA: 
VISADO POR (DBA): 
FECHA APROBACIÓN DBA: 
COMENTARIOS DBA: 
TABLAS INVOLUCRADAS: ENCO_ENTIDAD_CONTRATANTE, RLUN_REBALSE_LUN
***********************************************************************/


ALTER procedure ENCO0001
(
       @EMPLEADOR varchar(250),
       @ID_TIPO_CONTRATO INT,
       @ID_REGION INT,
       @ID_COMUNA INT,
	   @ID_ECOL INT,
	   @DIRECCION VARCHAR(500),
	   @NUMERO VARCHAR(50),
	   @RESTO_DIRECCION VARCHAR(500),
	   @SOBRECUPO INT,
	   @TOTAL_LICENCIAS INT
)
AS
BEGIN

	--PRIMERO ACTUALIZAMOS LOS REGISTROS EN ENCO
	UPDATE 
		ENCO_ENTIDAD_CONTRATANTE_LUN SET
		RAZON_SOCIAL = @EMPLEADOR,
		TIPO_CONTRATANTE = @ID_TIPO_CONTRATO,
		REG_ID = @ID_REGION,
		COM_ID = @ID_COMUNA,
		DIRECCION = @DIRECCION,
		NUMERO_DIRECCION = @NUMERO,
		RESTO_DIRECCION = @RESTO_DIRECCION
	WHERE
		ID = @ID_ECOL

	UPDATE
		RLUN_REBALSE_LUN SET
		SOBRECUPO = @SOBRECUPO,
		TOTAL_LICENCIAS_INICIAL = @TOTAL_LICENCIAS
	WHERE
		ECOL_ID = @ID_ECOL

END
