USE [BDWebLun]
GO

/****** Object:  Table [dbo].[LGU_LOGIN_USUARIO]    Script Date: 21/05/2018 22:07:22 ******/
IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'LGU_LOGIN_USUARIO')
BEGIN
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[LGU_LOGIN_USUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_HORA_LOGIN] [datetime] NULL,
	[NOMBRE_USUARIO] [varchar](250) NULL,
	[ECOL_ID] [int] NULL,
	[ROL] [varchar](250) NULL,
	[TOKEN] [varchar](500) NULL,
	[FECHA_ENTERA] [int] NULL,
 CONSTRAINT [PK_LGU_LOGIN_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO