
USE [BDWebLun]
GO
	IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LREA0002]') AND type = N'P') 
	--Se crea encabezado vacio del SP en caso de ser nuevo
	exec('CREATE PROCEDURE [dbo].[LREA0002] AS BEGIN SET NOCOUNT ON; END')
GO
/****** Object:  StoredProcedure [dbo].[LREA0002]    Script Date: 10-07-2018 16:45:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/************************************************************************
NOMBRE DEL PROCEDIMIENTO: LREA0002
AUTOR: Victor Coronado
FECHA DE CREACIÓN: 20/07/2018
BASE DE DATOS: BDWEBLUN
OBJETIVO: OBTENER LAS LUNS DE RELUN Y REASIGNADAS PARA BUSQUEDA EN EL FRONT
FECHA DE MODIFICACIÓN: 
USUARIO DE MODIFICACIÓN: 
MOTIVO DE MODIFICACIÓN: 
VISADO POR (QA): 
FECHA APROBACIÓN QA: 
COMENTARIOS QA: 
VISADO POR (DBA): 
FECHA APROBACIÓN DBA: 
COMENTARIOS DBA: 
TABLAS INVOLUCRADAS: RELUN_REGISTRO_LUN, LREA_LICENCIA_REASIGNADA
***********************************************************************/


ALTER procedure LREA0002
(
	@RUN VARCHAR(20),
	@ECOL_ID INT
)
AS
BEGIN
--SELECT A LA RELUN

IF (SELECT MAX(ID) FROM LREA_LUN_REASIGNADA WHERE RUN = @RUN AND ECOL_ID_ORIGINAL = @ECOL_ID) > 0
BEGIN
	DECLARE @MAX_ID_LREA INT

	SET @MAX_ID_LREA = (SELECT MAX(ID) FROM LREA_LUN_REASIGNADA WHERE RUN = @RUN AND ECOL_ID_ORIGINAL = @ECOL_ID)
	SELECT 
		ID,
		RUN_FUNCIONARIO,
		ACTIVO,
		ELIMINADO,
		FECHA_ALTA,
		FECHA_BAJA,
		FECHA_CREACION,
		NOMBRE_FUNCIONARIO,
		PRIMER_APELLIDO,
		SEGUNDO_APELLIDO,
		ECOL_ID,
		0 AS REASIGNADA
		FROM 
		RELUN_REGISTRO_LUN
		WHERE 
		RUN_FUNCIONARIO = @RUN AND ECOL_ID = @ECOL_ID
	UNION ALL
	SELECT 
		ID,
		RUN AS RUN_FUNCIONARIO,
		ACTIVO,
		ELIMINADO,
		FECHA_ALTA,
		FECHA_BAJA,
		FECHA_REGISTRO AS FECHA_CREACION,
		NOMBRE_FUNCIONARIO,
		PRIMER_APELLIDO,
		SEGUNDO_APELLIDO,
		ECOL_ID_ORIGINAL AS ECOL_ID,
		1 AS REASIGNADA
	FROM
		LREA_LUN_REASIGNADA
	WHERE 
		RUN = @RUN AND ECOL_ID_ORIGINAL = @ECOL_ID
END
ELSE
BEGIN
SELECT 
	ID,
	RUN_FUNCIONARIO,
	ACTIVO,
	ELIMINADO,
	FECHA_ALTA,
	FECHA_BAJA,
	FECHA_CREACION,
	NOMBRE_FUNCIONARIO,
	PRIMER_APELLIDO,
	SEGUNDO_APELLIDO,
	ECOL_ID,
	0 AS REASIGNADA
	FROM 
	RELUN_REGISTRO_LUN
	WHERE 
	RUN_FUNCIONARIO = @RUN AND ECOL_ID = @ECOL_ID
END


END