
USE [BDWebLun]
GO
	IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RELUN0002]') AND type = N'P') 
	--Se crea encabezado vacio del SP en caso de ser nuevo
	exec('CREATE PROCEDURE [dbo].[RELUN0002] AS BEGIN SET NOCOUNT ON; END')
GO
/****** Object:  StoredProcedure [dbo].[RELUN0002]    Script Date: 09-07-2018 16:45:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/************************************************************************
NOMBRE DEL PROCEDIMIENTO: RELUN0002
AUTOR: Victor Coronado
FECHA DE CREACIÓN: 09/07/2018
BASE DE DATOS: BDWEBLUN
OBJETIVO: modifica una licencia
FECHA DE MODIFICACIÓN: 
USUARIO DE MODIFICACIÓN: 
MOTIVO DE MODIFICACIÓN: 
VISADO POR (QA): 
FECHA APROBACIÓN QA: 
COMENTARIOS QA: 
VISADO POR (DBA): 
FECHA APROBACIÓN DBA: 
COMENTARIOS DBA: 
TABLAS INVOLUCRADAS: RELUN_REGISTRO_LUN
***********************************************************************/


ALTER procedure RELUN0002
(
	@ID INT,
	@RUN_FUNCIONARIO VARCHAR(20),
	@ACTIVO INT,
	@FECHA_ALTA DATETIME,
	@FECHA_BAJA DATETIME,
	@FECHA_CREACION DATETIME,
	@NOMBRE_FUNCIONARIO VARCHAR(500),
	@PRIMER_APELLIDO VARCHAR(500),
	@SEGUNDO_APELLIDO VARCHAR(500),
	@SEXO INT,
	@ECOL_ID INT,
	@ES_SOBRECUPO INT,
	@USUARIO_CREADOR VARCHAR(500),
	@ES_RAYEN int,
	@ES_RAYEN_COMUNITARIO int,
	@ES_FLORENCE int,
	@ELIMINADO INT
)
AS 
BEGIN
	update RELUN_REGISTRO_LUN set 
		RUN_FUNCIONARIO = @RUN_FUNCIONARIO, 
		ACTIVO = 1, 
		ELIMINADO = 0, 
		FECHA_ALTA = @FECHA_ALTA,
		FECHA_BAJA = @FECHA_BAJA, 
		FECHA_CREACION = @FECHA_CREACION, 
		NOMBRE_FUNCIONARIO = @NOMBRE_FUNCIONARIO, 
		PRIMER_APELLIDO = @PRIMER_APELLIDO,
		SEGUNDO_APELLIDO = @SEGUNDO_APELLIDO,  
		SEXO = @SEXO, 
		ECOL_ID = @ECOL_ID, 
		ES_SOBRECUPO = @ES_SOBRECUPO, 
		USUARIO_CREADOR = @USUARIO_CREADOR,
		ES_RAYEN = @ES_RAYEN, 
		ES_RAYEN_COMUNITARIO = @ES_RAYEN_COMUNITARIO, 
		ES_FLORENCE = @ES_FLORENCE
	WHERE 
		ID = @ID
END