
USE [BDWebLun]
GO
	IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RELUN0001]') AND type = N'P') 
	--Se crea encabezado vacio del SP en caso de ser nuevo
	exec('CREATE PROCEDURE [dbo].[RELUN0001] AS BEGIN SET NOCOUNT ON; END')
GO
/****** Object:  StoredProcedure [dbo].[RELUN0001]    Script Date: 01-06-2018 16:45:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/************************************************************************
NOMBRE DEL PROCEDIMIENTO: RELUN0001
AUTOR: Victor Coronado
FECHA DE CREACIÓN: 05/07/2018
BASE DE DATOS: BDWEBLUN
OBJETIVO: ENTREGA LA CANTIDAD DE LICENCIAS UTILIZADAS PARA UNA ENTIDAD CONTRATANTE DEPENDIENDO EL TIPO CONTRATO
FECHA DE MODIFICACIÓN: 
USUARIO DE MODIFICACIÓN: 
MOTIVO DE MODIFICACIÓN: 
VISADO POR (QA): 
FECHA APROBACIÓN QA: 
COMENTARIOS QA: 
VISADO POR (DBA): 
FECHA APROBACIÓN DBA: 
COMENTARIOS DBA: 
TABLAS INVOLUCRADAS: RELUN_REGISTRO_LUN, RLUN_REBALSE_LUN
***********************************************************************/


ALTER procedure RELUN0001
(
	@ECOL_ID INT
)
AS 
BEGIN
	--OBTENCION DE LOS TIPOS DE CONTRATOS
	DECLARE @TIPO_CONTRATO INT
	SET @TIPO_CONTRATO = (SELECT TIPO_CONTRATANTE FROM ENCO_ENTIDAD_CONTRATANTE_LUN WHERE ID = @ECOL_ID)
	/*
	TIPO_CONTRATO = 0 LUN NOMBRADA
	TIPO_CONTRATO = 1 LICENCIA REASIGNADA
	TIPO_CONTRATO = 2 LICENCIA CONCURRENTE
	*/
	IF (@TIPO_CONTRATO = 0)
		BEGIN
			select COUNT(*) AS UTILIZADAS from RELUN_REGISTRO_LUN where ECOL_ID = @ECOL_ID and ACTIVO = 1 and ELIMINADO = 0 and   (FECHA_BAJA >= GETDATE() or FECHA_BAJA is null)
		END
	IF (@TIPO_CONTRATO = 1)
		BEGIN
			select COUNT(*) AS UTILIZADAS from RELUN_REGISTRO_LUN where ECOL_ID = @ECOL_ID and ACTIVO = 1 and ELIMINADO = 0 and   (FECHA_BAJA >= GETDATE() or FECHA_BAJA is null)
		END
	IF (@TIPO_CONTRATO = 2)
		BEGIN
			SELECT TOTAL_LICENCIAS_INICIAL AS UTILIZADAS FROM RLUN_REBALSE_LUN WHERE ECOL_ID = @ECOL_ID
		END
END